-- MySQL Script generated by MySQL Workbench
-- Sat Nov 30 11:29:23 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema datawebbh
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `datawebbh` ;

-- -----------------------------------------------------
-- Schema datawebbh
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `datawebbh` DEFAULT CHARACTER SET utf8 ;
USE `datawebbh` ;

-- -----------------------------------------------------
-- Table `datawebbh`.`administrators`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `datawebbh`.`administrators` ;

CREATE TABLE IF NOT EXISTS `datawebbh`.`administrators` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `datawebbh`.`categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `datawebbh`.`categories` ;

CREATE TABLE IF NOT EXISTS `datawebbh`.`categories` (
  `id_category` VARCHAR(45) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_category`),
  UNIQUE INDEX `id_category_UNIQUE` (`id_category` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `datawebbh`.`products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `datawebbh`.`products` ;

CREATE TABLE IF NOT EXISTS `datawebbh`.`products` (
  `id_product` INT(11) NOT NULL AUTO_INCREMENT,
  `id_category` VARCHAR(45) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `size` VARCHAR(10) NULL DEFAULT NULL,
  `price` VARCHAR(10) NOT NULL,
  `note` VARCHAR(100) NULL DEFAULT NULL,
  `image` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_product`),
  UNIQUE INDEX `id_product_UNIQUE` (`id_product` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `datawebbh`.`orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `datawebbh`.`orders` ;

CREATE TABLE IF NOT EXISTS `datawebbh`.`orders` (
  `id_order` INT(11) NOT NULL AUTO_INCREMENT,
  `id_user` INT(11) NOT NULL,
  `id_product` INT(11) NOT NULL,
  `quantity` INT(11) NOT NULL,
  `amount` DECIMAL(10,2) NOT NULL,
  `created` DATE NOT NULL,
  PRIMARY KEY (`id_order`),
  INDEX `a_idx` (`id_product` ASC) VISIBLE,
  CONSTRAINT `a`
    FOREIGN KEY (`id_product`)
    REFERENCES `datawebbh`.`products` (`id_product`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `datawebbh`.`shippers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `datawebbh`.`shippers` ;

CREATE TABLE IF NOT EXISTS `datawebbh`.`shippers` (
  `id_shipper` INT(11) NOT NULL AUTO_INCREMENT,
  `id_card` VARCHAR(20) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `phone` VARCHAR(15) NULL DEFAULT NULL,
  `address` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id_shipper`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `datawebbh`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `datawebbh`.`users` ;

CREATE TABLE IF NOT EXISTS `datawebbh`.`users` (
  `id_user` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(16) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `phone` VARCHAR(12) NULL DEFAULT NULL,
  `address` VARCHAR(255) NULL DEFAULT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_user`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
